## This function should be able to cache the inverse of a matrix
## The cachesolve can recover the inverse from either the cache if 
## the inverse already has been computed and also the matrix has still not changed

## This function should be able to generate a unique "matrix" object capable of caching its inverse.

makeCacheMatrix <- function(x = matrix()) { #makeCacheMatrix consists of set, inv, setinv, and get inv
  inv<-NULL #to set inverse as NULL
  set<-function(y){
    x<<-y
    inv<<-NULL
  }
  get<-function()x #to get matrix x
  setinv <- function(inverse) {inv <<- inverse}
  getinv <- function() {
    inver<-ginv(x)
    inver%*%x #to get inverse of matrix
  }
  list(set = set, get = get, setinv = setinv, getinv = getinv)
}

## This same inverse of a special "matrix" generated by the Cache Matrix 
## is computed with this function. It can recover the inverse from either 
## the cache if the inverse has already been computed

cacheSolve <- function(x, ...) {
  inv<-x$getinv()
  if(!is.null(inv)){ #to check if inverse is NULL
    message("getting cached data.")
    return(inv) #to return inverse value
  }
  data<-x$get()
  inv<-solve(data, ...) #to solve inverse value
  x$setinv(inv)
  inv
}